(eval-when-compile    (require 'color-theme))
(defun amy-color-theme ()
  (interactive)
  (color-theme-install
   '(amy-color-theme
     ((background-color . "#1f0022")
      (background-mode . dark)
      (border-color . "#ffffff")
      (cursor-color . "#6a64fb")
      (foreground-color . "#c7cfff")
      (mouse-color . "white"))
     (fringe ((t (:background "#1f0022"))))
     (mode-line ((t (:foreground "#000000" :background "#dbdbdb"))))
     (region ((t (:background "#4e020f"))))
     (font-lock-builtin-face ((t (:foreground "#c7cfff"))))
     (font-lock-comment-face ((t (:foreground "#7f5085"))))
     (font-lock-function-name-face ((t (:foreground "#4796a1"))))
     (font-lock-keyword-face ((t (:foreground "#7b99ff"))))
     (font-lock-string-face ((t (:foreground "#999999"))))
     (font-lock-type-face ((t (:foreground"#4796a1"))))
     (font-lock-variable-name-face ((t (:foreground "#c7cfff"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'amy-color-theme)
