(eval-when-compile (require 'color-theme))
(defun blackboard-color-theme ()
  (interactive)
  (color-theme-install
   '(blackboard-color-theme
     ((background-color . "#020d21")
      (background-mode . dark)
      (border-color . "#0e152c")
      (cursor-color . "#ffffff")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#020d21"))))
     (mode-line ((t (:foreground "#000000" :background "#ffffff"))))
     (region ((t (:background "#1e3c74"))))
     (font-lock-builtin-face ((t (:foreground "#fbde2a"))))
     (font-lock-comment-face ((t (:foreground "#aeaeae"))))
     (font-lock-function-name-face ((t (:foreground "#fa6300"))))
     (font-lock-keyword-face ((t (:foreground "#fbde2a"))))
     (font-lock-string-face ((t (:foreground "#60ce3b"))))
     (font-lock-type-face ((t (:foreground "#d8fa3b"))))
     (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     
     (sgml-doctype-face ((t (:foreground "orange" :italic nil))))
     (sgml-end-tag-face ((t (:foreground "greenyellow" :italic nil))))
     (sgml-entity-face ((t (:foreground "gold" :italic nil))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray20" :italic nil))))
     (sgml-sgml-face ((t (:foreground "yellow" :italic nil))))
     (sgml-start-tag-face ((t (:foreground "mediumspringgreen" :italic nil))))
     )))
(provide 'blackboard-color-theme)
