(eval-when-compile (require 'color-theme))
(defun cyan-color-theme ()
  (interactive)
  (color-theme-install
   '(cyan-color-theme
     ((background-color . "#0c0c0c")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#ffffff")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#000"))))
     (mode-line ((t (:foreground "#000000" :background "#ffffff"))))
     (region ((t (:background "#1e3c74"))))
     (font-lock-builtin-face ((t (:foreground "#902500"))))
     (font-lock-comment-face ((t (:foreground "#aeaeae"))))
     (font-lock-function-name-face ((t (:foreground "#154fe4"))))
     (font-lock-keyword-face ((t (:foreground "#00ff42"))))
     (font-lock-string-face ((t (:foreground "#009d81"))))
     (font-lock-type-face ((t (:foreground "#d8fa3b"))))
     (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     
     (sgml-doctype-face ((t (:foreground "orange" :italic nil))))
     (sgml-end-tag-face ((t (:foreground "greenyellow" :italic nil))))
     (sgml-entity-face ((t (:foreground "gold" :italic nil))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray20" :italic nil))))
     (sgml-sgml-face ((t (:foreground "yellow" :italic nil))))
     (sgml-start-tag-face ((t (:foreground "mediumspringgreen" :italic nil))))
     )))
(cyan-color-theme)
(set-face-background 'hl-line "#08303b")
(provide 'cyan-color-theme)

