(eval-when-compile    (require 'color-theme))
(defun purple-color-theme ()
  (interactive)
  (color-theme-install
   '(purple-color-theme
     ((background-color . "#000")
      (background-mode . dark)
      (border-color . "#0e152c")
      (cursor-color . "#fffff")
      (foreground-color . "#ffffff")
      (mouse-color . "white"))
     (fringe ((t (:background "#6c319d"))))
     (mode-line ((t (:foreground "#000000" :background "#dbdbdb"))))
     (region ((t (:background "#2f5085"))))
     (font-lock-builtin-face ((t (:foreground "#ffc1a0"))))
     (font-lock-comment-face ((t (:foreground "#d57dc9"))))
     (font-lock-function-name-face ((t (:foreground "#595dfc"))))
     (font-lock-keyword-face ((t (:foreground "#ffc1a0"))))
     (font-lock-string-face ((t (:foreground "#d1552f"))))
     (font-lock-type-face ((t (:foreground "#ffc1a0"))))
     (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'purple-color-theme)