(eval-when-compile    (require 'color-theme))
(defun twilight-color-theme ()
  (interactive)
  (color-theme-install
   '(twilight-color-theme
     ((background-color . "#131313")
      (background-mode . dark)
      (border-color . "#0e152c")
      (cursor-color . "#ffffff")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#131313"))))
     (mode-line ((t (:foreground "#000000" :background "#dbdbdb"))))
     (region ((t (:background "#3b4043"))))
     
     (font-latex-string-face ((t (:bold t :weight semi-bold :foreground "#88985f"))))
     (font-latex-warning-face ((t (:bold t :weight semi-bold :background "#f90000"))))
     
     (font-lock-builtin-face ((t (:foreground "#be6a46"))))
     (font-lock-comment-face ((t (:foreground "#5e5960"))))
     (font-lock-constant-face ((t (:foreground "#be6a46"))))
     (font-lock-doc-face ((t (:bold t :foreground "#88985f" :weight semi-bold))))
     (font-lock-function-name-face ((t (:foreground "#907036"))))
     (font-lock-keyword-face ((t (:foreground "#cca95d"))))
     (font-lock-preprocessor-face ((t (:foreground "#00ccdd"))))
     (font-lock-string-face ((t (:foreground "#88985f"))))
     (font-lock-type-face ((t (:foreground "#907036"))))
     (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
     (font-lock-warning-face ((t (:bold t :foreground "#00CC00" :weight semi-bold))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'twilight-color-theme)
